<!DOCTYPE html>
<html>
<head>
    <title>Unittest Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="text-capitalize">Unittest Results</h2>
                <p class='attribute'><strong>Start Time: </strong>2020-08-27 20:02:52</p>
                <p class='attribute'><strong>Duration: </strong>313.80 s</p>
                <p class='attribute'><strong>Summary: </strong>Total: 5, Pass: 1, Fail: 2, Error: 2</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-10 col-md-10">
                <table class='table table-hover table-responsive'>
                    <thead>
                        <tr>
                            <th>__main__.ViewProductDetails</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class='danger'>
                            <td class="col-xs-10">test_AMZN_Search_TC_001_load_home_page</td>
                            <td class="col-xs-1">
                                <span class="label label-danger" style="display:block;width:40px;">Fail</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">AssertionError: 'Amazon' not found in ''</p><p style="color:maroon;">Traceback (most recent call last):
  File "/home/asmita/Desktop/Amazon/tests/unit_tests/AllTests.py", line 20, in test_AMZN_Search_TC_001_load_home_page
    self.assertIn("Amazon", driver.title)
AssertionError: 'Amazon' not found in ''
</p>
                            </td>
                        </tr>
                        <tr class='danger'>
                            <td class="col-xs-10">test_AMZN_Search_TC_002_search_for_a_term</td>
                            <td class="col-xs-1">
                                <span class="label label-danger" style="display:block;width:40px;">Fail</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">AssertionError: 'WD My Passport 4TB' not found in 'Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in'</p><p style="color:maroon;">Traceback (most recent call last):
  File "/home/asmita/Desktop/Amazon/tests/unit_tests/AllTests.py", line 30, in test_AMZN_Search_TC_002_search_for_a_term
    self.assertIn(self.search_term,self.driver.title)
AssertionError: 'WD My Passport 4TB' not found in 'Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in'
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_AMZN_Search_TC_003_add_item_to_cart</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ElementNotInteractableException: Message: Element <img class="s-image" src="https://m.media-amazon.com/images/I/91zYlmkap9L._AC_UY218_.jpg"> could not be scrolled into view
</p><p style="color:maroon;">Traceback (most recent call last):
  File "/home/asmita/Desktop/Amazon/tests/unit_tests/AllTests.py", line 40, in test_AMZN_Search_TC_003_add_item_to_cart
    self.driver.find_element_by_xpath("(//div[@class='sg-col-inner']//img[contains(@data-image-latency,'s-product-image')])[2]").click()
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <img class="s-image" src="https://m.media-amazon.com/images/I/91zYlmkap9L._AC_UY218_.jpg"> could not be scrolled into view

</p>
                            </td>
                        </tr>
                        <tr class='success'>
                            <td class="col-xs-10">test_AMZN_Search_TC_004_delete_item_from_cart</td>
                            <td class="col-xs-1">
                                <span class="label label-success" style="display:block;width:40px;">Pass</span>
                            </td>
                            <td class="col-xs-1">
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_AMZN_Search_TC_005_test_signin_to_checkout</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">TimeoutException: Message: Connection refused (os error 111)
</p><p style="color:maroon;">Traceback (most recent call last):
  File "/home/asmita/Desktop/Amazon/tests/unit_tests/AllTests.py", line 13, in setUp
    self.driver = webdriver.Firefox(executable_path="/home/asmita/Desktop/Amazon/drivers/geckodriver")
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/asmita/.local/share/virtualenvs/Amazon-4RHo9XSU/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Connection refused (os error 111)

</p>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                Total: 5, Pass: 1, Fail: 2, Error: 2 -- Duration: 313.80 s
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('td').on('click', '.btn', function(e){
                e.preventDefault();
                e.stopImmediatePropagation();
                var $this = $(this);
                var $nextRow = $this.closest('tr').next('tr');
                $nextRow.slideToggle("fast");
                $this.text(function(i, text){
                    if (text === 'View') {
                        return 'Hide';
                    } else {
                        return 'View';
                    };
                });
            });
        });
    </script>
</body>
</html